[package]
name = "hgl-program"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[package.metadata.hgl]
line-budget = 2200

[lints]
workspace = true

[dependencies]
hgl-source = { path = "../hgl-source" }
hgl-documentation = { path = "../hgl-documentation" }
hgl-library = { path = "../hgl-library" }
hgl-rust = { path = "../hgl-rust" }
hgl-value-check = { path = "../hgl-value-check" }
