[package]
name = "hgl-program"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[package.metadata.hgl]
line-budget = 2200

[lints]
workspace = true

[dependencies]
hgl-library-files = { path = "../hgl-library-files" }
hgl-source = { path = "../hgl-source" }
hgl-documentation = { path = "../hgl-documentation" }
hgl-library = { path = "../hgl-library" }
hgl-rust = { path = "../hgl-rust" }
hgl-value-check = { path = "../hgl-value-check" }
hgl-value-types = { path = "../hgl-value-types" }
hgl-value-bind = { path = "../hgl-value-bind" }
hgl-value-eval = { path = "../hgl-value-eval" }
hgl-struct-check = { path = "../hgl-struct-check" }
hgl-body-check = { path = "../hgl-body-check" }
hgl-flow-check = { path = "../hgl-flow-check" }
hgl-delta-check = { path = "../hgl-delta-check" }
hgl-endpoint-check = { path = "../hgl-endpoint-check" }
hgl-type-sizes = { path = "../hgl-type-sizes" }
hgl-eval-data = { path = "../hgl-eval-data" }
hgl-value-access = { path = "../hgl-value-access" }
hgl-harness-ir = { path = "../hgl-harness-ir" }
hgl-rust-preparation = { path = "../hgl-rust-preparation" }
hgl-local-check = { path = "../hgl-local-check" }
hgl-wiring-locals = { path = "../hgl-wiring-locals" }
