// Generated by tools/stdlib_fixtures.py; edit cases.json.
use hgl_testkit::cases::{Case, Slice};
use hgl_types::ScalarValue::I64;
pub(super) const CASES: &[Case] = &[
    Case { name: "bit_and_waits_for_both", source: "NAT-4, stdlib/cases.json",
        node: "hgraph.operators.bit_and.i64", scalars: &[],
        inputs: &[("lhs", &[Some(I64(6)), None, Some(I64(-1)), None, Some(I64(7)), Some(I64(7))]), ("rhs", &[None, Some(I64(3)), None, Some(I64(7)), None, None])], expected: &[None, Some(I64(2)), Some(I64(3)), Some(I64(7)), Some(I64(7)), Some(I64(7))],
        cycles: None, slice: Slice::P2 },
    Case { name: "sample_only_on_signal", source: "NAT-4, stdlib/cases.json",
        node: "hgraph.std.sample.i64", scalars: &[],
        inputs: &[("signal", &[None, Some(I64(1)), None, Some(I64(1)), Some(I64(1))]), ("ts", &[Some(I64(1)), Some(I64(2)), Some(I64(3)), Some(I64(4)), None])], expected: &[None, Some(I64(2)), None, Some(I64(4)), Some(I64(4))],
        cycles: None, slice: Slice::P2 },
    Case { name: "sample_waits_for_value", source: "NAT-4, stdlib/cases.json",
        node: "hgraph.std.sample.i64", scalars: &[],
        inputs: &[("signal", &[Some(I64(1)), None, Some(I64(0)), None, Some(I64(0))]), ("ts", &[None, Some(I64(7)), None, Some(I64(8)), None])], expected: &[None, None, Some(I64(7)), None, Some(I64(8))],
        cycles: None, slice: Slice::P2 },
    Case { name: "dedup_zero_and_idle", source: "NAT-4, stdlib/cases.json",
        node: "hgraph.std.dedup.i64", scalars: &[],
        inputs: &[("ts", &[None, Some(I64(0)), Some(I64(0)), None, Some(I64(1)), Some(I64(1)), Some(I64(0))])], expected: &[None, Some(I64(0)), None, None, Some(I64(1)), None, Some(I64(0))],
        cycles: None, slice: Slice::P2 },
];
