[package]
name = "hgl-atomic"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
[package.metadata.hgl]
line-budget = 180
[dependencies]
hgl-shapes = { path = "../hgl-shapes" }
hgl-types = { path = "../hgl-types" }
hgl-bindings = { path = "../hgl-bindings" }
hgl-global-value = { path = "../hgl-global-value" }
[lints]
workspace = true
