[package]
name = "hgl-value-bind"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[package.metadata.hgl]
line-budget = 500

[lints]
workspace = true

[dependencies]
hgl-source = { path = "../hgl-source" }
hgl-library = { path = "../hgl-library" }
hgl-rust-ir = { path = "../hgl-rust-ir" }
hgl-value-types = { path = "../hgl-value-types" }
