use crate::model::{Body, Function, Guard, Statement, Value};
use crate::{CheckedModule, Diagnostic};

/// Emit resolved HGL as a Rust module using the existing runtime interfaces.
/// The containing crate supplies `Provider`, implementing the emitted `Native` trait.
pub fn emit_rust(module: &CheckedModule) -> Result<String, Vec<Diagnostic>> {
    let mut errors: Vec<_> = module
        .functions
        .iter()
        .filter(|function| function.native && function.body.is_none())
        .map(|function| Diagnostic {
            source: module.sources[function.source].clone(),
            start: function.span.start,
            end: function.span.end,
            message: "native declaration requires a selected implementation part".into(),
        })
        .collect();
    for function in &module.functions {
        let public = function.native || (function.exported && !node(function));
        let reserved = |name: &str| matches!(name, "self" | "Self" | "super" | "crate");
        if public
            && (reserved(&function.name)
                || function.parameters.iter().any(|parameter| {
                    reserved(&parameter.name)
                        || (!function.native
                            && matches!(parameter.name.as_str(), "registry" | "builder"))
                })
                || (!function.native && function.name == "register"))
        {
            errors.push(Diagnostic {
                source: module.sources[function.source].clone(),
                start: function.span.start,
                end: function.span.end,
                message: "public name conflicts with a Rust binding name in this slice".into(),
            });
        }
    }
    if !errors.is_empty() {
        return Err(errors);
    }
    let mut out = vec![String::from("// Generated by hglc; do not edit.\n")];
    out.push(
        "/// Native implementation selected by the containing library.\npub trait Native {\n"
            .to_owned(),
    );
    for function in module.functions.iter().filter(|f| f.native) {
        out.push(format!(
            "/// HGL native value helper `{}`.\nfn r#{}({}){};\n",
            function.name,
            function.name,
            public_parameters(function),
            if function.result { " -> i64" } else { "" }
        ));
    }
    out.push(("}\n/// Register the generated node implementations.\npub fn register(registry: &mut hgl_describe::Registry) -> Result<(), hgl_describe::BuildError> {\n").to_owned());
    for (index, function) in module.functions.iter().enumerate() {
        if node(function) {
            out.push(format!("registry.register::<Node{index}>()?;\n"));
        }
    }
    out.push(("Ok(())\n}\n").to_owned());
    for (index, function) in module.functions.iter().enumerate() {
        if function.native {
            continue;
        }
        if let Some(body) = function.body.as_ref().filter(|body| body.guard.is_some()) {
            emit_node(module, index, body, &mut out);
        }
        emit_construction(module, index, &mut out);
    }
    Ok(out.concat())
}
fn node(function: &Function) -> bool {
    function.body.as_ref().is_some_and(|b| b.guard.is_some())
}
fn public_parameters(function: &Function) -> String {
    function
        .parameters
        .iter()
        .map(|parameter| format!("r#{}: i64", parameter.name))
        .collect::<Vec<_>>()
        .join(", ")
}
fn parameters(function: &Function, graph: bool) -> String {
    function
        .parameters
        .iter()
        .enumerate()
        .map(|(index, p)| {
            let ty = if graph && !p.constant {
                "hgl_describe::NodeRef"
            } else {
                "i64"
            };
            format!("arg{index}: {ty}")
        })
        .collect::<Vec<_>>()
        .join(", ")
}
fn qualified(module: &CheckedModule, function: &Function) -> String {
    format!("{}.{}", module.name, function.name)
}
fn emit_node(module: &CheckedModule, index: usize, body: &Body, out: &mut Vec<String>) {
    let function = &module.functions[index];
    out.push(format!("#[derive(Debug)]\nstruct Node{index} {{\n"));
    for (arg, parameter) in function.parameters.iter().enumerate() {
        out.push(format!(
            "arg{arg}: {},\n",
            if parameter.constant {
                "i64"
            } else {
                "hgl_store::In<i64>"
            }
        ));
    }
    if function.result {
        out.push(("output: hgl_store::Out<i64>,\n").to_owned());
    }
    out.push(format!("}}\nimpl hgl_kernel::Node for Node{index} {{\n"));
    if body.start {
        out.push(("fn start(&mut self, ctx: &mut hgl_kernel::Ctx<'_>) -> hgl_kernel::NodeResult {\nctx.schedule_in(hgl_types::EngineDelta::from_micros(0))\n}\n").to_owned());
    }
    out.push(
        ("fn eval(&mut self, ctx: &mut hgl_kernel::Ctx<'_>) -> hgl_kernel::NodeResult {\n")
            .to_owned(),
    );
    let inputs: Vec<_> = function
        .parameters
        .iter()
        .enumerate()
        .filter(|(_, p)| !p.constant)
        .map(|(i, _)| i)
        .collect();
    let guard = if body.guard == Some(Guard::Scheduled) {
        "ctx.is_scheduled_now()".to_owned()
    } else if inputs.is_empty() {
        "false".to_owned()
    } else {
        inputs
            .iter()
            .map(|i| format!("ctx.modified(self.arg{i})"))
            .collect::<Vec<_>>()
            .join(" || ")
    };
    out.push(format!("if {guard} {{\n"));
    statements(module, index, true, out);
    out.push(("}\nOk(())\n}\n}\n").to_owned());
    emit_metadata(module, index, body, out);
}
fn emit_metadata(module: &CheckedModule, index: usize, body: &Body, out: &mut Vec<String>) {
    let function = &module.functions[index];
    out.push(format!("impl hgl_describe::Buildable for Node{index} {{\nfn node_type() -> hgl_types::NodeType {{\nhgl_types::NodeType {{\nname: {:?},\ninputs: vec![", qualified(module, function)));
    for parameter in function.parameters.iter().filter(|p| !p.constant) {
        out.push(format!(
            "({:?}, hgl_types::TsType::Ts(hgl_types::ScalarType::I64)),",
            parameter.name
        ));
    }
    out.push(("],\nscalars: vec![").to_owned());
    for parameter in function.parameters.iter().filter(|p| p.constant) {
        out.push(format!(
            "({:?}, hgl_types::ScalarType::I64),",
            parameter.name
        ));
    }
    out.push(("],\n").to_owned());
    if function.result {
        out.push(("output: Some(hgl_types::TsType::Ts(hgl_types::ScalarType::I64)),\n").to_owned());
    }
    if body.guard == Some(Guard::Scheduled) {
        out.push(("active_inputs: Some(vec![]),\n").to_owned());
    }
    out.push(format!(
        "uses_scheduler: {},\n..hgl_types::NodeType::default()\n}}\n}}\n",
        body.scheduler
    ));
    out.push(("fn build(ports: &mut hgl_describe::Ports<'_>) -> Result<Self, hgl_describe::BuildError> {\nOk(Self {\n").to_owned());
    for (arg, parameter) in function.parameters.iter().enumerate() {
        out.push(format!(
            "arg{arg}: ports.{}({:?})?,\n",
            if parameter.constant {
                "scalar"
            } else {
                "input"
            },
            parameter.name
        ));
    }
    if function.result {
        out.push(("output: ports.output()?,\n").to_owned());
    }
    out.push(("})\n}\n}\n").to_owned());
}
fn emit_construction(module: &CheckedModule, index: usize, out: &mut Vec<String>) {
    let function = &module.functions[index];
    let params = parameters(function, true);
    let signature = if params.is_empty() {
        String::new()
    } else {
        format!(", {params}")
    };
    out.push(format!("fn construct_{index}(builder: &mut hgl_describe::Builder<'_>{signature}) -> Result<{}, hgl_describe::BuildError> {{\n",
        if function.result { "hgl_describe::NodeRef" } else { "()" }));
    if node(function) {
        out.push(format!(
            "let node = builder.node({:?}, &[",
            qualified(module, function)
        ));
        for (arg, parameter) in function
            .parameters
            .iter()
            .enumerate()
            .filter(|(_, p)| p.constant)
        {
            out.push(format!(
                "({:?}, hgl_types::ScalarValue::I64(arg{arg})),",
                parameter.name
            ));
        }
        out.push(("])?;\n").to_owned());
        for (arg, parameter) in function
            .parameters
            .iter()
            .enumerate()
            .filter(|(_, p)| !p.constant)
        {
            out.push(format!(
                "builder.connect(arg{arg}, node, {:?})?;\n",
                parameter.name
            ));
        }
        out.push(
            (if function.result {
                "Ok(node)\n"
            } else {
                "Ok(())\n"
            })
            .to_owned(),
        );
    } else {
        statements(module, index, false, out);
        if !function.result {
            out.push(("Ok(())\n").to_owned());
        }
    }
    out.push(("}\n").to_owned());
    if function.exported && !node(function) && function.parameters.iter().all(|p| p.constant) {
        let public = public_parameters(function);
        let signature = if public.is_empty() {
            String::new()
        } else {
            format!(", {public}")
        };
        out.push(format!("/// Construct HGL graph `{}` without running it.\npub fn r#{}(registry: &hgl_describe::Registry{signature}) -> Result<hgl_describe::GraphDescription, hgl_describe::BuildError> {{\nlet mut builder = hgl_describe::Builder::new({:?}, registry);\nconstruct_{index}(&mut builder", function.name, function.name, qualified(module, function)));
        for parameter in &function.parameters {
            out.push(format!(", r#{}", parameter.name));
        }
        out.push((")?;\nbuilder.finish()\n}\n").to_owned());
    }
}
fn statements(module: &CheckedModule, function: usize, in_node: bool, out: &mut Vec<String>) {
    let mut local = 0;
    let mut temporary = 0;
    for statement in &module.bodies[function] {
        let value = match statement {
            Statement::Let(value) | Statement::Call(value) | Statement::Return(value) => value,
        };
        let code = if in_node {
            expression(module, function, true, value)
        } else {
            graph_value(module, function, value, out, &mut temporary)
        };
        match statement {
            Statement::Let(_) => {
                out.push(format!("let local{local} = {code};\n"));
                local += 1;
            }
            Statement::Call(_) => {
                if in_node {
                    out.push(format!("{code};\n"));
                }
            }
            Statement::Return(_) => {
                if in_node {
                    out.push(format!("ctx.set(self.output, {code});\nreturn Ok(());\n"));
                } else {
                    out.push(format!("Ok({code})\n"));
                }
            }
        }
    }
}
fn graph_value(
    module: &CheckedModule,
    function: usize,
    value: &Value,
    out: &mut Vec<String>,
    temporary: &mut usize,
) -> String {
    let Value::Call(index, arguments) = value else {
        return expression(module, function, false, value);
    };
    let arguments = arguments
        .iter()
        .map(|value| graph_value(module, function, value, out, temporary))
        .collect::<Vec<_>>()
        .join(", ");
    let call = format!(
        "construct_{index}(builder{}{arguments})?",
        if arguments.is_empty() { "" } else { ", " }
    );
    if !module.functions[*index].result {
        out.push(format!("{call};\n"));
        return "()".into();
    }
    let name = format!("wire{}", *temporary);
    *temporary += 1;
    out.push(format!("let {name} = {call};\n"));
    name
}

fn expression(module: &CheckedModule, function: usize, in_node: bool, value: &Value) -> String {
    match value {
        Value::Integer(value) => format!("{value}_i64"),
        Value::Local(index) => format!("local{index}"),
        Value::Parameter(index) => {
            if !in_node {
                format!("arg{index}")
            } else if module.functions[function].parameters[*index].constant {
                format!("self.arg{index}")
            } else {
                format!("ctx.get(self.arg{index})")
            }
        }
        Value::Call(index, arguments) => {
            let arguments = arguments
                .iter()
                .map(|v| expression(module, function, in_node, v))
                .collect::<Vec<_>>()
                .join(", ");
            if module.functions[*index].native {
                format!(
                    "<crate::Provider as Native>::r#{}({arguments})",
                    module.functions[*index].name
                )
            } else {
                format!(
                    "construct_{index}(builder{}{})?",
                    if arguments.is_empty() { "" } else { ", " },
                    arguments
                )
            }
        }
    }
}
