[package]
name="hgl-std-native"
version="0.0.0"
edition.workspace=true
rust-version.workspace=true
publish.workspace=true
[package.metadata.hgl]
line-budget=700
[lints]
workspace=true
[dependencies]
hgl-calendar={path="../hgl-calendar"}
hgl-kernel={path="../hgl-kernel"}
hgl-types={path="../hgl-types"}
hgl-store={path="../hgl-store"}
