[package]
name = "hgl-rust-structs"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
[package.metadata.hgl]
line-budget = 230
[lints]
workspace = true
[dependencies]
hgl-rust-prepared-values = { path = "../hgl-rust-prepared-values" }
hgl-source = { path = "../hgl-source" }
