[package]
name = "hgl-recursive-types"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
[package.metadata.hgl]
line-budget = 350
[lints]
workspace = true
[dependencies]
hgl-shape-obligations = { path = "../hgl-shape-obligations" }
hgl-value-access = { path = "../hgl-value-access" }
hgl-enums = { path = "../hgl-enums" }
hgl-source = { path = "../hgl-source" }
hgl-library = { path = "../hgl-library" }
hgl-struct-names = { path = "../hgl-struct-names" }
