[package]
name = "hgl-type-shape"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
[package.metadata.hgl]
line-budget = 300
[lints]
workspace = true

[dependencies]
hgl-nominal-batch = { path = "../hgl-nominal-batch" }
hgl-type-syntax = { path = "../hgl-type-syntax" }
hgl-types = { path = "../hgl-types" }
