[package]
name = "hgl-keys"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
[package.metadata.hgl]
line-budget = 500
[lints]
workspace = true
[dependencies]
hgl-global-value = { path = "../hgl-global-value" }
hgl-types = { path = "../hgl-types" }
[dev-dependencies]
hgl-alloc-count = { path = "../hgl-alloc-count" }
