"""Render the same reasoned cases for Rust and the reference HGL compiler."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPUS = ROOT / 'docs/compiler/stdlib'


def render():
    cases = json.loads((CORPUS / 'cases.json').read_text())
    rust = ['// Generated by tools/stdlib_fixtures.py; edit cases.json.',
            'use hgl_testkit::cases::{Case, Slice};',
            'use hgl_types::ScalarValue::I64;',
            'pub(super) const CASES: &[Case] = &[']
    hgl = ['# Expected ticks from cases.json.',
           'module conformance.stdlib part tests']
    implementations = {'bit_and_i64': 'hgraph.operators.bit_and.i64',
                       'sample_i64': 'hgraph.std.sample.i64',
                       'dedup_i64': 'hgraph.std.dedup.i64'}
    for c in cases:
        ticks = lambda xs: '&[' + ', '.join('None' if x is None else f'Some(I64({x}))' for x in xs) + ']'
        inputs = ', '.join(f'("{k}", {ticks(v)})' for k, v in c['inputs'].items())
        rust += [f'    Case {{ name: "{c["name"]}", source: "NAT-4, stdlib/cases.json",',
                 f'        node: "{implementations[c["node"]]}", scalars: &[],',
                 f'        inputs: &[{inputs}], expected: {ticks(c["expected"])},',
                 '        cycles: None, slice: Slice::P2 },']
        seq = lambda xs: '[' + ', '.join('_' if x is None else str(x) for x in xs) + ']'
        args = ', '.join(f'{k}: {seq(v)}' for k, v in c['inputs'].items())
        hgl += [f'test {c["name"]} {{',
                f'    assert eval({c["node"]}, {args}) == {seq(c["expected"])}', '}']
    rust += ['];', '']
    hgl += ['']
    return {ROOT / 'crates/hgl-stdlib/tests/support/cases.rs': '\n'.join(rust),
            CORPUS / 'cases.hgl': '\n'.join(hgl)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, text in render().items():
        if args.check:
            if not path.exists() or path.read_text() != text:
                raise SystemExit('Stale fixture: ' + str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)


if __name__ == '__main__':
    main()
