[package]
name = "hgl-rust-generators"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[package.metadata.hgl]
line-budget = 500

[lints]
workspace = true

[dependencies]
hgl-rust-finite-domains = { path = "../hgl-rust-finite-domains" }
hgl-rust-windows = { path = "../hgl-rust-windows" }
hgl-rust-source-slots = { path = "../hgl-rust-source-slots" }
hgl-rust-deltas = { path = "../hgl-rust-deltas" }
hgl-source = { path = "../hgl-source" }
hgl-rust-ir = { path = "../hgl-rust-ir" }
hgl-rust-values = { path = "../hgl-rust-values" }
