[package]
name = "hgl-rust-preparation"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
[package.metadata.hgl]
line-budget = 300
[lints]
workspace = true
[dependencies]
hgl-rust-value-convert = { path = "../hgl-rust-value-convert" }
hgl-rust-collections = { path = "../hgl-rust-collections" }
hgl-rust-recursive-convert = { path = "../hgl-rust-recursive-convert" }
hgl-source = { path = "../hgl-source" }
hgl-rust-ir = { path = "../hgl-rust-ir" }
hgl-harness-ir = { path = "../hgl-harness-ir" }
hgl-rust-layouts = { path = "../hgl-rust-layouts" }
hgl-rust-values = { path = "../hgl-rust-values" }
hgl-rust-checked-data={path="../hgl-rust-checked-data"}
hgl-rust-families = { path = "../hgl-rust-families" }
